### ISSUE TITLE
Upload finished gives js exception

### ISSUE THREAD

**Issue by michielpost** [json-editor/json-editor#743]
### General information
I upgraded from a 2.0 beta to 2.2.1 today and my upload fields are now failing.
The file gets uploaded, but the call to `cbs.success(filename)` results in a javascript error.

This can be reproduced using the provided upload example.
https://json-editor.github.io/json-editor/upload.html

- json-editor version: 2.2.1 (latest)

This bug is introduced in version 2.2.0. It works correctly with version 2.1.0.

### Expected behavior
Upload should finish successfully.

### Steps to reproduce the behavior
Reproduce: 
Use the upload_default field.
https://json-editor.github.io/json-editor/upload.html

When calling `cbs.success` it returns this error on the console:
```
Uncaught TypeError: this.setValue is not a function
    at Object.success (jsoneditor.min.js:18)
```
